Repository agntcy/dir, pull requests merged in 2025-05, with the labels that each got.

#111 fix: flaky e2e test
  server/routing/internal/p2p/server_test.go
Labels: bug

#113 refactor: separate api bindings
  API_SPEC.md
  Taskfile.yml
  USAGE.md
  api/buf.gen.yaml
  api/buf.yaml
  api/go.mod
  api/go.sum
  api/go/core/v1alpha1/agent.go
  api/go/core/v1alpha1/agent.pb.go
  api/go/core/v1alpha1/extension.go
  api/go/core/v1alpha1/extension.pb.go
  api/go/core/v1alpha1/locator.go
  api/go/core/v1alpha1/locator.pb.go
  api/go/core/v1alpha1/oasf-validator/skills.go
  api/go/core/v1alpha1/object.go
  api/go/core/v1alpha1/object.pb.go
  api/go/core/v1alpha1/object_test.go
  api/go/core/v1alpha1/skill.go
  api/go/core/v1alpha1/skill.pb.go
  api/go/go.mod
  api/go/go.sum
  api/go/routing/v1alpha1/peer.pb.go
  api/go/routing/v1alpha1/routing_service.pb.go
  api/go/routing/v1alpha1/routing_service_grpc.pb.go
  api/go/store/v1alpha1/store_service.pb.go
  api/go/store/v1alpha1/store_service_grpc.pb.go
  api/go/version/version.go
  api/proto/core/v1alpha1/agent.proto
  api/proto/core/v1alpha1/extension.proto
  api/proto/core/v1alpha1/locator.proto
  api/proto/core/v1alpha1/object.proto
  api/proto/core/v1alpha1/skill.proto
  api/proto/routing/v1alpha1/peer.proto
  api/proto/routing/v1alpha1/routing_service.proto
  api/proto/store/v1alpha1/store_service.proto
  api/routing/v1alpha1/routing_service.pb.gw.go
  api/store/v1alpha1/store_service.pb.gw.go
  cli/go.mod
  cli/go.sum
  client/go/client.go
  client/go/config.go
  client/go/go.mod
  client/go/go.sum
  client/go/routing.go
  client/go/store.go
  e2e/go.mod
  e2e/go.sum
  hub/go.mod
  hub/go.sum
  server/go.mod
  server/go.sum
Labels: enhancement

#114 fix: list command outputs with network flag
  .github/workflows/reusable-test-e2e.yaml
  .github/workflows/reusable-test.yaml
  Taskfile.yml
  e2e/client_test.go
  e2e/config/config.go
  e2e/dirctl_network_cmd_test.go
  e2e/dirctl_network_deploy_test.go
  e2e/dirctl_test.go
  e2e/go.mod
  e2e/suite_test.go
  server/routing/handler.go
  server/routing/handler_test.go
  server/routing/routing_local.go
  server/routing/routing_remote.go
  server/routing/rpc/rpc.go
  server/routing/test_utils.go
Labels: bug

#116 refactor: distroless docker images
  cli/Dockerfile
  server/Dockerfile
Labels: enhancement

#115 docs: python sdk
  client/python/README.md
  client/python/example.py
Labels: documentation

#124 fix: python sdk
  client/python/README.md
Labels: bug, documentation

#133 fix: python sdk
  tools/python/client/example.py
Labels: bug

#135 fix: python sdk
  tools/python/client/README.md
Labels: documentation

#137 feat: ctl hub initialize
  cli/cmd/initialize/initialize.go
  cli/cmd/initialize/repo/repo.go
  cli/cmd/root.go
Labels: enhancement
