Repository agntcy/dir, pull requests merged in 2025-10, with the labels that each got.

#469 fix(dir): locator based remote record search
  server/routing/ROUTING.md
  server/routing/cleanup_core_test.go
  server/routing/query_matching_test.go
  server/routing/routing_local.go
  server/routing/routing_remote.go
  server/routing/search_simple_test.go
Labels: size/S

#491 feat(dir): encode referrers
  Taskfile.yml
  api/core/v1/referrer.go
  api/core/v1/referrer_types.go
  api/sign/v1/public_key.go
  api/sign/v1/public_key.pb.go
  api/sign/v1/signature.go
  api/store/v1/store_service.pb.go
  cli/cmd/pull/pull.go
  client/go.mod
  client/sign.go
  client/verify.go
  hub/go.mod
  hub/go.sum
  proto/agntcy/dir/sign/v1/public_key.proto
  proto/agntcy/dir/store/v1/store_service.proto
  sdk/dir-js/package-lock.json
  sdk/dir-js/package.json
  sdk/dir-js/src/index.ts
  sdk/dir-js/src/models/sign_v1.ts
  sdk/dir-js/src/utils.ts
  sdk/dir-js/test/client.test.ts
  sdk/dir-py/agntcy/dir_sdk/client/test_client.py
  sdk/dir-py/agntcy/dir_sdk/models/sign_v1.py
  sdk/dir-py/agntcy/dir_sdk/utils.py
  sdk/dir-py/pyproject.toml
  sdk/dir-py/uv.lock
  sdk/examples/example-js/package-lock.json
  server/controller/sign.go
  server/controller/store.go
  server/store/oci/referrers.go
  server/store/oci/signatures.go
  server/store/oci/types.go
  server/sync/monitor/monitor.go
  server/types/store.go
  utils/go.mod
  utils/go.sum
  utils/oci/oci.go
Labels: buf skip breaking

#495 feat(dir): Implement Connection Manager and Remove Custom Peer Discovery
  Taskfile.yml
  install/docker/apiserver.env
  server/routing/internal/p2p/constants.go
  server/routing/internal/p2p/dht.go
  server/routing/internal/p2p/discover.go
  server/routing/internal/p2p/host.go
  server/routing/internal/p2p/server.go
  server/routing/pubsub/manager.go
  server/routing/routing_remote.go
Labels: kind/feature, area/dir

#503 feat(dir): Enable AutoRelay, Hole Punching, and mDNS for Better Peer Connectivity
  server/go.mod
  server/go.sum
  server/routing/internal/p2p/constants.go
  server/routing/internal/p2p/host.go
  server/routing/internal/p2p/server.go
Labels: kind/feature, area/dir
