Repository agntcy/dir, pull requests merged in 2025-09, with the labels that each got.

#342 refactor: Remove Legacy List API and Migrate to RecordQuery-Based System
  api/proto/routing/v1/routing_service.proto
  api/routing/v1/routing_service.pb.go
  api/types/v1alpha1/domain.pb.go
  api/types/v1alpha1/feature.pb.go
  api/types/v1alpha1/locator.pb.go
  api/types/v1alpha1/record.pb.go
  api/types/v1alpha1/signature.pb.go
  api/types/v1alpha1/skill.pb.go
  cli/cmd/list/digest.go
  cli/cmd/list/info/info.go
  cli/cmd/list/network.go
  cli/cmd/list/peer.go
  client/routing.go
  e2e/client_test.go
  e2e/dirctl_network_deploy_test.go
  e2e/utils/common.go
  server/controller/routing.go
  server/routing/CONSTANTS_USAGE.md
  server/routing/ROUTING.md
  server/routing/label_metadata.go
  server/routing/label_metadata_test.go
  server/routing/metrics.go
  server/routing/routing.go
  server/routing/routing_local.go
  server/routing/routing_local_test.go
  server/routing/routing_remote.go
  server/routing/rpc/rpc.go
  server/routing/test_utils.go
  server/routing/validators/constants.go
  server/routing/validators/validators.go
  server/routing/validators/validators_test.go
  server/types/routing.go
Labels: buf skip breaking

#362 feat: Implement Search API for network-wide record discovery using RecordQuery interface
  README.md
  Taskfile.yml
  api/proto/routing/v1/record_query.proto
  api/routing/v1/record_query.pb.go
  cli/README.md
  cli/cmd/list/digest.go
  cli/cmd/list/info/info.go
  cli/cmd/list/info/options.go
  cli/cmd/list/list.go
  cli/cmd/list/network.go
  cli/cmd/list/options.go
  cli/cmd/list/peer.go
  cli/cmd/root.go
  cli/cmd/routing/info.go
  cli/cmd/routing/list.go
  cli/cmd/routing/publish.go
  cli/cmd/routing/routing.go
  cli/cmd/routing/search.go
  cli/cmd/routing/unpublish.go
  client/routing.go
  e2e/README.md
  e2e/client_test.go
  e2e/dirctl_local_routing_test.go
  e2e/dirctl_network_deploy_test.go
  e2e/dirctl_remote_search_test.go
  e2e/utils/cli.go
  e2e/utils/common.go
  server/controller/routing.go
  server/routing/ROUTING.md
  server/routing/cleanup_core_test.go
  server/routing/cleanup_tasks.go
  server/routing/constants.go
  server/routing/handler.go
  server/routing/label_metadata.go
  server/routing/label_metadata_test.go
  server/routing/labels/operations.go
  server/routing/labels/types.go
  server/routing/labels/types_test.go
  server/routing/metrics.go
  server/routing/query_matching.go
  server/routing/query_matching_test.go
  server/routing/routing.go
  server/routing/routing_local.go
  server/routing/routing_remote.go
  server/routing/routing_remote_or_logic_test.go
  server/routing/search_simple_test.go
  server/routing/test_utils.go
  server/routing/utils.go
  server/routing/validators/constants.go
  server/routing/validators/validators.go
  server/routing/validators/validators_test.go
  server/types/routing.go
Labels: buf skip breaking

#384 chore: find better place for proto APIs
  .github/workflows/buf-ci.yaml
  Taskfile.yml
  proto/buf.gen.yaml
  proto/buf.lock
  proto/buf.yaml
  proto/core/v1/record.proto
  proto/routing/v1/peer.proto
  proto/routing/v1/publication_service.proto
  proto/routing/v1/record_query.proto
  proto/routing/v1/routing_service.proto
  proto/search/v1/record_query.proto
  proto/search/v1/search_service.proto
  proto/sign/v1/sign_service.proto
  proto/store/v1/store_service.proto
  proto/store/v1/sync_service.proto
Labels: buf skip breaking

#424 chore: bump OASF SDK version to v0.0.5
  api/go.mod
  api/go.sum
  cli/go.mod
  cli/go.sum
  client/go.mod
  client/go.sum
  e2e/go.mod
  e2e/go.sum
  server/go.mod
  server/go.sum
Labels: dependencies

#405 feat(sdk): add spiffe support to JS/TS/Python SDKs
  .dockerignore
  Taskfile.yml
  docker-bake.hcl
  e2e/sdk/Dockerfile
  e2e/sdk/chart/Chart.yaml
  e2e/sdk/chart/templates/_helpers.tpl
  e2e/sdk/chart/templates/clusterspiffeids.yaml
  e2e/sdk/chart/templates/job.yaml
  e2e/sdk/chart/values.yaml
  sdk/dir-js/README.md
  sdk/dir-js/package-lock.json
  sdk/dir-js/package.json
  sdk/dir-js/rollup.config.mjs
  sdk/dir-js/src/client/client.ts
  sdk/dir-js/test/client.test.ts
  sdk/dir-py/README.md
  sdk/dir-py/agntcy/dir_sdk/client/client.py
  sdk/dir-py/agntcy/dir_sdk/client/config.py
  sdk/dir-py/agntcy/dir_sdk/client/test_client.py
  sdk/dir-py/pyproject.toml
  sdk/dir-py/uv.lock
Labels: enhancement

#451 feat(dir/api): support storage of generic record referrers
  api/core/v1/record.pb.go
  api/sign/v1/sign_service.pb.go
  api/sign/v1/sign_service_grpc.pb.go
  api/sign/v1/signature.pb.go
  api/store/v1/store_service.pb.go
  proto/agntcy/dir/core/v1/record.proto
  proto/agntcy/dir/sign/v1/sign_service.proto
  proto/agntcy/dir/sign/v1/signature.proto
  proto/agntcy/dir/store/v1/store_service.proto
Labels: size/L

#458 docs(dir): remove broken links from readme
  README.md
Labels: size/XS

#464 fix(utils/cosign): migrate cosign signature attachment to OCI 1.1 referrers spec
  client/verify.go
  e2e/network/02_sync_test.go
  server/store/oci/referrers.go
  utils/cosign/sign.go
Labels: size/S
