Repository agntcy/dir, pull requests merged in 2025-06, with the labels that each got.

#160 feat: improve grpc error handling
  USAGE.md
  server/controller/routing.go
  server/controller/store.go
  server/routing/routing.go
  server/routing/routing_local.go
  server/routing/routing_local_test.go
  server/routing/routing_remote.go
  server/routing/rpc/rpc.go
  server/store/localfs/localfs.go
  server/store/oci/oci.go
  server/store/oci/oci_test.go
  server/store/store.go
  server/types/store.go
Labels: enhancement, go

#186 feat: add local search service
  api/core/v1alpha1/skill.go
  api/proto/search/v1alpha2/record_query.proto
  api/proto/search/v1alpha2/search_service.proto
  api/search/v1alpha2/record_query.go
  api/search/v1alpha2/record_query.pb.go
  api/search/v1alpha2/search_service.pb.go
  api/search/v1alpha2/search_service_grpc.pb.go
  cli/cmd/root.go
  cli/cmd/search/options.go
  cli/cmd/search/query.go
  cli/cmd/search/search.go
  client/client.go
  client/search_v1alpha2.go
  e2e/dirctl_test.go
  server/Dockerfile
  server/controller/store.go
  server/controller/v1alpha2/search.go
  server/go.mod
  server/go.sum
  server/search/sqlite/config/config.go
  server/search/sqlite/record.go
  server/search/sqlite/record_test.go
  server/search/sqlite/skill.go
  server/search/v1alpha1/record.go
  server/server.go
  server/types/search.go
  tools/python/api/pyproject.toml
  tools/python/api/search/v1alpha2/record_query_pb2.py
  tools/python/api/search/v1alpha2/record_query_pb2.pyi
  tools/python/api/search/v1alpha2/record_query_pb2_grpc.py
  tools/python/api/search/v1alpha2/search_service_pb2.py
  tools/python/api/search/v1alpha2/search_service_pb2.pyi
  tools/python/api/search/v1alpha2/search_service_pb2_grpc.py
  tools/python/api/uv.lock
Labels: enhancement

#194 fix: local search
  cli/cmd/search/search.go
  e2e/dirctl_test.go
  server/search/sqlite/record.go
Labels: bug
